# Generated by Django 4.1.7 on 2023-04-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessevent',
            old_name='user',
            new_name='doorUser',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='doorUser',
        ),
    ]
