# Generated by Django 4.2.1 on 2023-05-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0002_rename_user_accessevent_dooruser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessevent',
            old_name='doorUser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='doorUser',
            new_name='user',
        ),
    ]
