# Generated by Django 4.2.1 on 2023-06-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0003_rename_dooruser_accessevent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorman.userprofile'),
        ),
    ]
